### ISSUE TITLE
Support for 2-bytes ASN1 tags

### ISSUE THREAD

**Issue by danslu** [codemations/Asn1#16]
I would like to request about support for 2bytes tags. 

eg. 0x1F27

![image](https://user-images.githubusercontent.com/12549112/165750171-f6204aba-194e-4e9c-91f1-cf68e9106e3c.png)

**Comment by danslu** [comment]
![image](https://user-images.githubusercontent.com/12549112/165894438-7edca517-5f3f-4115-b894-037f0d858a5b.png)

**Comment by codemations** [comment]
The example above shows how high value tag can be created but the value passed to the constructor seems to be encoded instead of raw high tag value.
When the passed tag value is `39` then the resulting encoded tag is `0x9F27`.
